name 'wordpeppers'
version '0.1.0'
supports 'ubuntu', '>= 14.04'

depends 'apt'
depends 'nginx'
depends 'php'
depends 'composer'
depends 'wp-cli'
depends 'php-fpm'
depends 'mysql2_chef_gem'
depends 'database'
